### ISSUE TITLE
Gatsby plugin rendered Pro+SPA code produces syntax error

### ISSUE THREAD

**Issue by jjunco-otf** [newrelic/gatsby-plugin-newrelic#16]
## Description

When instrumentationType configured in gatsby-config is set to proAndSPA, rendered agent is executed and produces the following error:

Uncaught SyntaxError: Unexpected token ')'

Crack staff engineer Harrison McGuire found that the error was originating at this line:

a=/Version/(S+)s+Safari/

...which should be:

a=/Version\/(\S+)\s+Safari/

It seems some of this was fixed in your repo several months ago in src/browser-agents/latest.js, but the faulty line remains in browser-agents/latest.js

## Steps to Reproduce

- Install v1.0.4 of Gatsby New Relic plugin.
- Configure in gatsby-config with proAndSPA instrumentationType

## Expected Behaviour

No error.

## Relevant Logs / Console output

Uncaught SyntaxError: Unexpected token ')'

## Your Environment

MacOs Catalina 10.15.6
React v16.5.2
Gatsby v2.24.56
New Relic Gatsby plugin v1.03
Viewed on Chrome v85

**Comment by thannes** [comment]
Confirmed. I'm having the issue too.

**Comment by debojitroy** [comment]
Is the fix released yet?

**Comment by devfreddy** [comment]
@jjunco-otf @debojitroy @thannes There's a new version (`v1.05`) released on npm with the fixed agent code, please update, and try again. Thanks!

**Comment by jjunco-otf** [comment]
Success!  Thank you.
