### ISSUE TITLE
Invalid Javascript is generated causing Uncaught SyntaxError

### ISSUE THREAD

**Issue by shawncarr** [newrelic/gatsby-plugin-newrelic#2]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The javascript that is injected into the HTML does not seem to be valid resulting in a syntax error. 

## Steps to Reproduce

- `gatsby new newrelictest`
- cd newrelictest 
- yarn add https://github.com/newrelic/gatsby-plugin-newrelic.git
- add configuration

```{
      resolve: 'gatsby-plugin-newrelic',
      options: {
        instrumentationType: 'lite', // also tried pro and proAndSPA
        configs: {
          production: {
             accountId: '<some integer>',
             trustKey: '<some integer>',
             agentID: '<some integer>',
             licenseKey: '<the license key>',
             applicationID: '<some integer>',
             beacon: 'bam.nr-data.net',
             errorBeacon: 'bam.nr-data.net'
          },
        },
      },
    }
```

- `GATSBY_NEWRELIC_ENV=production yarn build`
- Run website
- :sob: 

## Expected Behaviour

NewRelic JS to load and report information

## Relevant Logs / Console output

`Uncaught SyntaxError: Unexpected token ')'`

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Chrome 83.0.4103.116 & Firefox 77.0.1

## Additional context

**Comment by tangollama** [comment]
Hey @shawncarr. Thanks for reporting this. We'll look into it ASAP.

**Comment by danielgolden** [comment]
#6 closes this issue. Thanks again, @shawncarr!
