### ISSUE TITLE
[Gatsby-Plugin] README is outdated

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/gatsby-plugin-newrelic#20]
## Summary

It seems the README is a bit out-of-date. https://rpm.newrelic.com is no longer since it now redirects to https://one.newrelic.com. If would be great to update the steps to include the new experience.

### Acceptance Criteria

- [x] project readme accurately reflects current functionality of the plugin.

**Comment by jpvajda** [comment]
This can be done along with #31 , that will get to know the plugin
