### ISSUE TITLE
Update to list Gatsby v3 as a peer dependency

### ISSUE THREAD

**Issue by rogervera** [newrelic/gatsby-plugin-newrelic#21]
Haven't looked into any breaking changes that could occur yet, but Gatsby v3 just released.

See: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers

https://github.com/newrelic/gatsby-plugin-newrelic/blob/6b5a4ea6d08c054586c4370c1d0be32659ebb5a1/package.json#L22

**Comment by cyberious** [comment]
Agreed, I am blocked on some upgrade with this, most likely will remove the package until fixed.

**Comment by roadlittledawn** [comment]
This was done in https://github.com/newrelic/gatsby-plugin-newrelic/pull/22
