### ISSUE TITLE
All browser agent data has stopped reporting

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/gatsby-plugin-newrelic#24]
### Issue

We are no longer seeing `PageView` event data in our dashboards for the browser agent  for our sites using this plugin., the problem seem to start  : somewhere between Jul 12, 11a m— Jul 13, 11am

### Refs

https://github.com/newrelic/gatsby-plugin-newrelic

### Steps to reproduce

- go to a dashboard that tracks events from our sites 
- view dashboard
- see the missing data>

### NRQL

`SELECT count(*) FROM PageView where appName = 'docs.newrelic.com' since 1 month ago TIMESERIES 1 day`

`SELECT count(*) FROM PageView where appName = 'opensource.newrelic.com' since 1 month ago TIMESERIES 1 day`

`SELECT count(*) FROM PageView where appName = 'developer.newrelic.com' since 1 month ago TIMESERIES 1 day`

### Expected

- [ ] Data is visible in our dashboards

**Comment by roadlittledawn** [comment]
looks like we load the current version of the browser agent ([v1210](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1210/))

**Comment by roadlittledawn** [comment]
fyi: i’m pretty stumped why the browser agent is not sending data. 
- we haven’t made any changes in gatsby-plugin-newrelic recently, 
- don’t see any changes in any of the site repos / theme repo that would cause this (Browser agent data isn’t being sent for any of the sites), 
- and we’re loading the current version of browser agent snippet

and like Liz said, tessen `TessenAction` events are reporting to the tessen account. just no Browser data to Developer Enablement or Developer Experience accounts (which is where the Browser agent is configured to send data for our Gatsby sites). didn't see anyone reporting similar issue in #internal_feedback either.

**Comment by rudouglas** [comment]
The agent seems to be inserting into the page source ok, and not seeing any NRIntegrationErrors in the platform. 

I'm not sure if this is the issue, but it looks like [gatsby-plugin-newrelic](https://github.com/newrelic/gatsby-plugin-newrelic/blob/main/src/browser-agents/latest.js) is loading up [v1167](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1167/) which is a bit behind the latest version. I tried altering the plugins code but couldn't get it to load the latest version for some reason, so not sure if this will fix the issue

<img width="743" alt="Screenshot 2021-07-16 at 14 00 02" src="https://user-images.githubusercontent.com/17122543/125951915-316567ab-ffe1-4636-8de7-033d5e5cfac8.png">

**Comment by roadlittledawn** [comment]
@rudouglas nice catch on version number! that was one of my first hunches, but for some reason i thought i saw the current version being used in a network call in the browser.

**Comment by roadlittledawn** [comment]
i created a new standalone app to get the latest snippet and noticed in the `NREUM.info` the beacon value is:

```staging-bam-cell.nr-data.net```

in gatsby-config.js we use:

```staging-bam.nr-data.net```

**Comment by rudouglas** [comment]
Ye I originally thought I saw the latest version loading as well, but I couldn't find were I was seeing that again 🤷 

Freddy had already done work on getting the latest agent version installed [here](https://github.com/newrelic/gatsby-plugin-newrelic/pull/10). This is installable using `npm i gatsby-plugin-newrelic@alpha` which I tested out. It looks like it's loading the most recent agent in correctly, but there's still no data reporting.

I tried creating a new API key but no dice, so that's not the issue.

I also tried running NRDiag on this and it showed success

```
Success  Browser/Agent/GetSource
Success  Browser/Agent/Detect
```

As a next step i've asked in #help-browser-agent internally for troubleshooting help
https://newrelic.slack.com/archives/C0193KAHHAS/p1626690368259000

**Comment by rudouglas** [comment]
This seems to have been an internal issue as confirmed [here](https://newrelic.slack.com/archives/C015SQKMN3G/p1626701253040400). The mirror makers in all staging cells needed to be restarted, and it looks like data is now flowing through.

I think we should discuss implementing freddy's alpha changes to always be on the latest Browser Agent version as a separate ticket

**Comment by roadlittledawn** [comment]
yep, i also see performance data and event data via NRQL for all 3 sites.
