### ISSUE TITLE
Update ReadMe for GATSBY_NEWRELIC_ENV

### ISSUE THREAD

**Issue by shawncarr** [newrelic/gatsby-plugin-newrelic#3]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Currently, the ReadMe doesn't have any information about the `GATSBY_NEWRELIC_ENV` variable which causing the sample config to be invalid. It also should include an example of how to build locally while setting those variables. 

## Possible Solution

`GATSBY_NEWRELIC_ENV=production yarn build` 

```
{
      resolve: 'gatsby-plugin-newrelic',
      options: {
        instrumentationType: 'proAndSPA',
        configs: {
          production: {
             accountId: '<some integer>',
             trustKey: '<some integer>',
             agentID: '<some integer>',
             licenseKey: '<the license key>',
             applicationID: '<some integer>',
             beacon: 'bam.nr-data.net',
             errorBeacon: 'bam.nr-data.net'
          },
        },
      },
    }
```

## Additional context

This will help people getting started.

**Comment by danielgolden** [comment]
Thanks for creating this issue, @shawncarr. Any chance you can submit a PR for this (would be super helpful)!

**Comment by danielgolden** [comment]
@devfreddy Any thoughts on this?

**Comment by devfreddy** [comment]
Closing, will be updated as of merging #10
