### ISSUE TITLE
Add Gatsby v4 support to Plugin

### ISSUE THREAD

**Issue by tristandenyer** [newrelic/gatsby-plugin-newrelic#44]
[NOTE]: # Building the Gatsby v4 web app with `"gatsby-plugin-newrelic": "^2.0.2"` gives a WARN of `Plugin gatsby-plugin-newrelic is not compatible with your gatsby version 4.3.0 - It requires gatsby@^3.0.0` and `npm i` gives a WARN of `gatsby-plugin-newrelic@2.0.2 requires a peer of gatsby@^3.0.0 but none is installed.`

## Summary

[NOTE]: # `"gatsby-plugin-newrelic": "^2.0.2"` appears to work well with Gatsby v4

## clear WARNs from terminal

[NOTE]: # no WARNs in terminal for building with Gatsby v4.x
[TIP]:  # 

## Possible Solution

[NOTE]: # change line ( https://github.com/newrelic/gatsby-plugin-newrelic/blob/main/package.json#L22 ) to be `"gatsby": "^3.0.0 || ^4.0.0` to support either major version

## Additional context

[TIP]:  # This can give the false impression that the plugin does not work with Gatsby v4, but in fact it does.

### Acceptance Criteria

- [x] Review PR and approve 
- [x] creating an alpha release of this package[ on NPM](https://www.npmjs.com/package/gatsby-build-newrelic)
- [ ] provide that to @herecydev for testing purposes from PR #45 
- [ ] If testing passes, then publish this version to NPM as a new version release.

**Comment by jpvajda** [comment]
@tristandenyer thanks for reporting this, we have an open PR in review to address this enhancement.

**Comment by jpvajda** [comment]
@herecydev 👋

**Comment by jpvajda** [comment]
It doesn't look like the `next` version updated on NPM after this merge, so I'm going to try to sync with @devfreddy on what may have gone wrong in our workflow here.

**Comment by jpvajda** [comment]
It seems we have all the correct updates made, but we are getting a failure on authentication to NPM now, for OTP. I'll look into this as well.

```
'npm ERR! This operation requires a one-time password from your authenticator.\n' +
    'npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.\n' +
    'npm ERR! If you already provided a one-time password then it is likely that you either typoed\n' +
    'npm ERR! it, or it timed out. Please try again.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/runner/.npm/_logs/2022-01-06T20_11_34_361Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
```

**Comment by jpvajda** [comment]
I'm working on resolving this issue with some internal teams.

**Comment by jpvajda** [comment]
The [release job ran successfully](https://github.com/newrelic/gatsby-plugin-newrelic/runs/4743313324?check_suite_focus=true), 🥳   but NPM didn't update 😭  So I'm now looking into what may be occurring with NPM. 

```
[8:20:27 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[8:20:27 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:20:27 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:20:27 PM] [semantic-release] › ℹ  Found git tag v2.1.0 associated with version 2.1.0 on branch next
[8:20:27 PM] [semantic-release] › ℹ  Found 0 commits since last release
```

**Comment by jpvajda** [comment]
@tristandenyer / @herecydev  We've now published a next version of this plugin that will support Gatsby 4. if you come across any issues, please let us know by reporting an [issue here.](https://github.com/newrelic/gatsby-plugin-newrelic/issues)

https://www.npmjs.com/package/gatsby-plugin-newrelic/v/2.1.1

Sorry for the delays on this, we actually had to work through some internal process improvements for this repository, but now it's all sorted out.
