### ISSUE TITLE
publish gatsby newrelic plugin next to latest on NPM

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-plugin-newrelic#51]
relates to https://github.com/newrelic/gatsby-plugin-newrelic/issues/44

### Acceptance Criteria

- [x] confirm with @tristandenyer /  @herecydev  the `next` branch is available on [NPM](https://www.npmjs.com/package/gatsby-plugin-newrelic/v/2.1.1)
- [x] Once confirm this is working for a few users we can publish the next version to latest by merging next into main branch.

**Comment by tristandenyer** [comment]
@jpvajda we ticked the NR package up to latest 2.1.1, and [made a PR](https://github.com/postmanlabs/postman-docs/pull/3810). My team will test in BETA and let you know how things go. Thx!

**Comment by jpvajda** [comment]
@tristandenyer thank you! We appreciate that. Once we confirm this version is working we can the bump it to the latest release and merge this next branch into main.

**Comment by herecydev** [comment]
@jpvajda looks all good from where we are 👍

**Comment by jpvajda** [comment]
@herecydev Thank you!
